In [2]:
import numpy as np

In [4]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [5]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [8]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [10]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
ar_ex = np.array([[[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0 ,1 ,2, 3],
...                            [4, 5, 6, 7]]])

In [14]:
ar_ex.ndim

3

In [15]:
ar_ex.size

24

In [16]:
ar_ex.shape

(3, 2, 4)

In [18]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [20]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [36]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

In [34]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [32]:
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [30]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [39]:
c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

In [41]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

basic array operations

In [47]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [48]:
data-ones

array([0, 1])

In [49]:
data*data

array([1, 4])

In [50]:
data/data

array([1., 1.])

In [52]:
a=np.array([1,2,3,4])
a.sum()

10

In [56]:
b=np.array([[1,2],[3,4]])
b.sum(axis=0)

array([4, 6])

In [57]:
b.sum(axis=1)

array([3, 7])

Broadcasting

In [58]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [60]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [61]:
data[0,1]

2

In [62]:
data[1:3]

array([[3, 4]])

In [63]:
data[0:2,0]

array([1, 3])

In [64]:
data.max()

4

In [65]:
data.min()

1

In [66]:
data.sum()

10

In [68]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [69]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [71]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [72]:
np.ones(3)

array([1., 1., 1.])

In [73]:
np.zeros(3)

array([0., 0., 0.])

In [74]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [77]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [78]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [79]:
unique_values, indices_list = np.unique(a,return_index= True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [80]:
unique_values, occurence_count=np.unique(a, return_counts=True)
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


In [82]:
a_2d= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [83]:
unique_value = np.unique(a_2d)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [84]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
unique_rows, indices, occurrence_count = np.unique(
a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
print(indices)

[0 1 2]


In [87]:
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


In [88]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [92]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [94]:
reversed_arr= np.flip(arr)
reversed_arr

array([[5, 4, 3],
       [2, 1, 0]])

In [95]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [97]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [98]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [99]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [100]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [101]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [103]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [105]:
a2 = x.ravel()
a2[0]=98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
